import type { CategoryDefinition } from "../types";

export const defaultCategories: CategoryDefinition[] = [
  {
    id: "brown-texts",
    name: "Brown Texts",
    mode: "mmt_content_mode",
    description: "Write-ready brown text for key hotel sections.",
    requiredResearchFields: ["distinct property highlights", "amenities", "location", "rooms", "dining"],
    outputFormat: "Structured brown text items with citations for every factual claim.",
    writingStyle: "MMT-ready, concise, factual, polished.",
    examples: [],
    doRules: ["Use only official website evidence.", "Keep claims traceable to source excerpts."],
    dontRules: ["Do not invent superlatives.", "Do not paraphrase source facts during extraction."],
    sourceEvidenceRequirements: ["Each output must include sourceUrl and sourceExcerpt."],
    missingInformationRules: ["Use not_found when source evidence is missing."],
    jsonSchemaDescription: "contentOutputs[] with type=brown_text plus supportingEvidence[].",
    isDefault: true,
    isActive: true
  },
  {
    id: "experience-cards",
    name: "Experience Cards",
    mode: "mmt_content_mode",
    description: "Guest experiences and highlights in card format.",
    requiredResearchFields: ["experiences", "activities", "wellness", "dining", "nearby attractions"],
    outputFormat: "Card-ready title, short copy, and cited evidence.",
    writingStyle: "Short, vivid, factual, source-grounded.",
    examples: [],
    doRules: ["Use exact activity and venue names as found."],
    dontRules: ["Do not add sensory claims that are not present on the website."],
    sourceEvidenceRequirements: ["Every card must cite a source excerpt."],
    missingInformationRules: ["Skip unsupported cards or mark required facts as not_found."],
    jsonSchemaDescription: "contentOutputs[] with type=experience_card plus supportingEvidence[].",
    isDefault: true,
    isActive: true
  },
  {
    id: "property-descriptions",
    name: "Property Descriptions",
    mode: "mmt_content_mode",
    description: "Detailed property descriptions for listing pages.",
    requiredResearchFields: ["overview", "location", "rooms", "amenities", "dining", "policies"],
    outputFormat: "Structured description sections with cited factual claims.",
    writingStyle: "Clear, listing-ready, factual.",
    examples: [],
    doRules: ["Preserve official names of rooms, restaurants, facilities, and policies."],
    dontRules: ["Do not merge similar room or amenity labels."],
    sourceEvidenceRequirements: ["Citations required for every field."],
    missingInformationRules: ["Mark absent fields as not_found."],
    jsonSchemaDescription: "contentOutputs[] with type=property_description plus sections[].",
    isDefault: true,
    isActive: true
  },
  ...[
    ["amenities", "Amenities", "Hotel facilities, services, wellness, etc."],
    ["room-types", "Room Types & Descriptions", "Room types, amenities, size, occupancy."],
    ["dining-restaurants", "Dining & Restaurants", "Restaurants, bars, cuisines, timings."],
    ["location-attractions", "Location & Nearby Attractions", "Address, nearby attractions, transport."],
    ["hotel-overview", "Hotel Overview / About", "Official overview and about-property details."],
    ["policies", "Policies", "Check-in/out, cancellation, child, pet, and other official policies."],
    ["images-media", "Images & Media", "Official images, galleries, videos, captions, and alt text when available."],
    ["reviews-ratings", "Reviews & Ratings", "Only official-website reviews or ratings, if available."],
    ["all-raw-categories", "All Categories", "All raw research categories above."]
  ].map(([id, name, description]) => ({
    id,
    name,
    mode: "raw_research_mode" as const,
    description,
    requiredResearchFields: [name],
    outputFormat: "Structured factual fields exactly as written on official website pages.",
    examples: [],
    doRules: ["Extract exact source wording.", "Include sourceUrl and sourceExcerpt for each value."],
    dontRules: ["Do not summarize extracted facts.", "Do not use third-party OTA data."],
    sourceEvidenceRequirements: ["Every field requires sourceUrl and sourceExcerpt."],
    missingInformationRules: ["Use not_found for missing official website information."],
    jsonSchemaDescription: "sections[].fields[] with exact source-backed values.",
    isDefault: true,
    isActive: true
  }))
];
